import { StyleSheet } from "react-native";

export const C = {
  light: {
    bg: "#f5f6f8",
    card: "#fff",
    text: "#18212b",
    muted: "#687482",
    border: "#d9dee5",
  },
  dark: {
    bg: "#12161b",
    card: "#1b222a",
    text: "#f0f3f6",
    muted: "#a1acb8",
    border: "#34404d",
  },
};

export const s = StyleSheet.create({
  safe: { flex: 1 },
  content: {
    width: "100%",
    maxWidth: 720,
    alignSelf: "center",
    padding: 24,
    gap: 20,
  },
  top: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  topActions: { flexDirection: "row", alignItems: "center", gap: 10 },
  brand: { flexDirection: "row", alignItems: "center", gap: 10 },
  mark: {
    backgroundColor: "#2f6fed",
    color: "#fff",
    fontSize: 22,
    fontWeight: "800",
    padding: 8,
    borderRadius: 8,
  },
  brandText: { fontSize: 20, fontWeight: "700" },
  theme: { fontSize: 22, padding: 8 },
  exit: { fontSize: 28, color: "#d9534f", paddingHorizontal: 8 },
  status: { flexDirection: "row", alignItems: "center", gap: 8 },
  dot: { width: 9, height: 9, borderRadius: 5, backgroundColor: "#2f9e68" },
  card: {
    marginTop: 30,
    padding: 24,
    borderRadius: 14,
    borderWidth: 1,
    gap: 16,
  },
  heading: { fontSize: 25, fontWeight: "700" },
  code: {
    alignItems: "center",
    padding: 18,
    backgroundColor: "#eef3ff",
    borderRadius: 10,
  },
  qrFrame: {
    width: 196,
    height: 196,
    marginTop: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#fff",
    borderRadius: 8,
  },
  codeValue: { fontSize: 22, fontWeight: "700", marginTop: 5 },
  input: {
    minHeight: 48,
    borderWidth: 1,
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
  },
  primary: {
    backgroundColor: "#2f6fed",
    minHeight: 48,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 20,
  },
  primaryText: { color: "#fff", fontWeight: "700", fontSize: 16 },
  disabled: { opacity: 0.5 },
  secondary: {
    minHeight: 48,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#9aa4af",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 20,
  },
  secondaryText: { color: "#52606d", fontWeight: "700", fontSize: 16 },
  workspace: { marginTop: 20, gap: 14 },
  tabs: { flexDirection: "row", gap: 8 },
  tab: {
    paddingVertical: 10,
    paddingHorizontal: 18,
    borderRadius: 8,
    backgroundColor: "#e8edf4",
  },
  activeTab: { backgroundColor: "#d8e5ff" },
  tabText: { color: "#334155", fontWeight: "700" },
  toolBlock: { gap: 14 },
  messageInput: {
    minHeight: 180,
    borderWidth: 1,
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
    textAlignVertical: "top",
  },
  footer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  filePicker: {
    minHeight: 130,
    borderWidth: 1,
    borderStyle: "dashed",
    borderRadius: 8,
    padding: 18,
    justifyContent: "center",
    gap: 8,
  },
  filePickerTitle: { fontWeight: "700", fontSize: 16 },
  transferTask: { borderWidth: 1, borderRadius: 8, padding: 14, gap: 12 },
  transferTitle: { fontWeight: "700", fontSize: 16 },
  transferFile: { gap: 5 },
  transferSummary: { gap: 4 },
  transferName: { fontWeight: "600" },
  transferStatus: { fontWeight: "600" },
  progressTrack: {
    height: 6,
    backgroundColor: "#d9dee5",
    borderRadius: 3,
    overflow: "hidden",
  },
  progressValue: { height: 6, backgroundColor: "#2f6fed" },
  incomingFile: {
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#d9dee5",
    gap: 3,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.45)",
    justifyContent: "center",
    padding: 24,
  },
  dialog: { borderRadius: 14, borderWidth: 1, padding: 22, gap: 16 },
});
