import { StyleSheet } from "react-native";

export const C = {
  light: {
    bg: "#f5f6f8",
    card: "#fff",
    text: "#18212b",
    muted: "#687482",
    border: "#d9dee5",
  },
  dark: {
    bg: "#12161b",
    card: "#1b222a",
    text: "#f0f3f6",
    muted: "#a1acb8",
    border: "#34404d",
  },
};

export const s = StyleSheet.create({
  safe: { flex: 1 },
  content: {
    width: "100%",
    maxWidth: 720,
    alignSelf: "center",
    padding: 24,
    gap: 20,
  },
  top: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  topActions: { flexDirection: "row", alignItems: "center", gap: 10 },
  settingsButton: {
    minWidth: 42,
    minHeight: 42,
    alignItems: "center",
    justifyContent: "center",
  },
  settingsIcon: { fontSize: 22 },
  brand: { flexDirection: "row", alignItems: "center", gap: 10 },
  mark: {
    backgroundColor: "#2f6fed",
    color: "#fff",
    fontSize: 22,
    fontWeight: "800",
    padding: 8,
    borderRadius: 8,
  },
  brandText: { fontSize: 20, fontWeight: "700" },
  theme: { fontSize: 22, padding: 8 },
  exit: { fontSize: 28, color: "#d9534f", paddingHorizontal: 8 },
  status: { flexDirection: "row", alignItems: "center", gap: 8 },
  dot: { width: 9, height: 9, borderRadius: 5, backgroundColor: "#2f9e68" },
  card: {
    marginTop: 30,
    padding: 24,
    borderRadius: 14,
    borderWidth: 1,
    gap: 16,
  },
  heading: { fontSize: 25, fontWeight: "700" },
  code: {
    alignItems: "center",
    padding: 18,
    borderRadius: 10,
  },
  qrFrame: {
    width: 196,
    height: 196,
    marginTop: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#fff",
    borderRadius: 8,
  },
  codeValue: { fontSize: 22, fontWeight: "700", marginTop: 5 },
  input: {
    minHeight: 48,
    paddingVertical: 12,
    paddingLeft: 12,
    paddingRight: 56,
    fontSize: 16,
  },
  inputContainer: {
    minHeight: 48,
    borderWidth: 1,
    borderRadius: 8,
    position: "relative",
    justifyContent: "center",
  },
  cameraButton: {
    position: "absolute",
    right: 4,
    top: 4,
    bottom: 4,
    width: 44,
    borderRadius: 6,
    alignItems: "center",
    justifyContent: "center",
  },
  cameraButtonText: { fontSize: 20, lineHeight: 24 },
  primary: {
    backgroundColor: "#2f6fed",
    minHeight: 48,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 20,
  },
  primaryText: { color: "#fff", fontWeight: "700", fontSize: 16 },
  disabled: { opacity: 0.5 },
  secondary: {
    minHeight: 48,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#9aa4af",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 20,
  },
  secondaryText: { color: "#52606d", fontWeight: "700", fontSize: 16 },
  workspace: { marginTop: 20, gap: 14 },
  tabs: { flexDirection: "row", gap: 8 },
  tab: {
    paddingVertical: 10,
    paddingHorizontal: 18,
    borderRadius: 8,
    backgroundColor: "#e8edf4",
  },
  activeTab: { backgroundColor: "#d8e5ff" },
  tabText: { color: "#334155", fontWeight: "700" },
  toolBlock: { gap: 14 },
  messageInput: {
    minHeight: 180,
    borderWidth: 1,
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
    textAlignVertical: "top",
  },
  footer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  filePicker: {
    minHeight: 130,
    borderWidth: 1,
    borderStyle: "dashed",
    borderRadius: 8,
    padding: 18,
    justifyContent: "center",
    gap: 8,
  },
  filePickerTitle: { fontWeight: "700", fontSize: 16 },
  transferTask: { borderWidth: 1, borderRadius: 8, padding: 14, gap: 12 },
  transferTitle: { fontWeight: "700", fontSize: 16 },
  transferFile: { gap: 5 },
  transferSummary: { gap: 4 },
  transferName: { fontWeight: "600" },
  transferStatus: {
    alignSelf: "flex-start",
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 3,
    fontWeight: "700",
    overflow: "hidden",
  },
  progressTrack: {
    height: 6,
    backgroundColor: "#d9dee5",
    borderRadius: 3,
    overflow: "hidden",
  },
  progressValue: { height: 6, backgroundColor: "#2f6fed" },
  incomingFile: {
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#d9dee5",
    gap: 3,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.45)",
    justifyContent: "center",
    padding: 24,
  },
  dialog: { borderRadius: 14, borderWidth: 1, padding: 22, gap: 16 },
  alertDialog: {
    width: "100%",
    maxWidth: 420,
    alignSelf: "center",
  },
  settingsDismiss: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
  },
  settingsDialog: {
    width: "100%",
    maxWidth: 420,
    alignSelf: "center",
    borderWidth: 1,
    borderRadius: 14,
    padding: 22,
    gap: 16,
  },
  settingsHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  settingsTitle: { fontSize: 21, fontWeight: "700" },
  settingsClose: { fontSize: 28, lineHeight: 30, paddingHorizontal: 4 },
  settingsLabel: { fontSize: 15, fontWeight: "600" },
  themeSegment: {
    flexDirection: "row",
    borderWidth: 1,
    borderRadius: 8,
    overflow: "hidden",
  },
  themeSegmentItem: {
    flex: 1,
    minHeight: 44,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 8,
  },
  themeSegmentSelected: { backgroundColor: "#2f6fed" },
  themeSegmentText: { color: "#52606d", fontWeight: "600", fontSize: 14 },
  themeSegmentSelectedText: { color: "#fff" },
  settingsDivider: { height: 1, marginVertical: 4 },
  settingsLogout: {
    minHeight: 44,
    alignItems: "flex-end",
    justifyContent: "center",
  },
  settingsLogoutText: { color: "#d9534f", fontSize: 15, fontWeight: "700" },
  scanner: { flex: 1, backgroundColor: "#000" },
  scannerCamera: { flex: 1 },
  scannerHeader: {
    position: "absolute",
    top: 56,
    left: 20,
    right: 20,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  scannerTitle: { color: "#fff", fontSize: 18, fontWeight: "700" },
  scannerClose: {
    minHeight: 42,
    borderRadius: 8,
    backgroundColor: "rgba(0,0,0,0.55)",
    justifyContent: "center",
    paddingHorizontal: 14,
  },
  scannerCloseText: { color: "#fff", fontWeight: "700" },
});
